# Generated by Django 4.0 on 2022-11-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.IntegerField()),
                ('profilePic', models.ImageField(default='default.jpg', upload_to='user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('scheduleTime', models.TimeField()),
                ('createdTime', models.TimeField(auto_now=True)),
                ('userSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='api.user')),
            ],
        ),
    ]
