# Generated by Django 4.1.3 on 2022-11-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=100)),
                ("scheduleTime", models.TimeField()),
                ("createdTime", models.TimeField(auto_now=True)),
            ],
        ),
    ]
