# Generated by Django 4.0 on 2022-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request',
            field=models.ManyToManyField(blank=True, to='api.User'),
        ),
    ]
