# Generated by Django 4.0 on 2022-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bodyPart',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
