# Generated by Django 4.0 on 2022-11-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_listing_bodypart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceptedRequest',
            field=models.ManyToManyField(blank=True, related_name='Accepted_Notification', to='api.User'),
        ),
    ]
